server:
 port: 8888

jasypt:
 encryptor:
  password: G0CvDz7oJn6


spring:
 jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

primarydb:
 uniqueResourceName: primary
 xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
 xaProperties:
  url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  username: ENC(i8QgEN4uOy2E1rHzrpSTYA==)
  password: ENC(i8QgEN4uOy2E1rHzrpSTYA==)
 exclusiveConnectionMode: true
 minPoolSize: 3
 maxPoolSize: 10
 testQuery: SELECT 1 FROM dual

secondarydb:
 uniqueResourceName: secondary
 xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
 xaProperties:
  url: jdbc:mysql://localhost:3306/mytest2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  username: ENC(i8QgEN4uOy2E1rHzrpSTYA==)
  password: ENC(i8QgEN4uOy2E1rHzrpSTYA==)
 exclusiveConnectionMode: true
 minPoolSize: 3
 maxPoolSize: 10
 testQuery: SELECT 1 FROM dual

mybatis:
 mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
 type-aliases-package: com.example.springbootdemo.model  # 注意：对应实体类的路径